### ISSUE TITLE
Serve does not work with global install on Windows

### ISSUE THREAD

**Issue by Sindhu-Vasireddy** [SolidBench/SolidBench.js#5]
When the dataset is generated and served directly from the solidbench npm package, it causes the following error stack:

> Error: Error while parsing file "C:\Users\Administrator\AppData\Roaming\npm\node_modules\@solid\community-server\config\util\auxiliary\no-acl.json": ENOENT: no such file or directory, stat 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\@solid\community-server\config\util\auxiliary\strategies\meta.json'
>     at Function.addPathToError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\solidbench\node_modules\componentsjs\lib\rdf\RdfParser.js:85:16)
>     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\solidbench\node_modules\componentsjs\lib\rdf\RdfStreamIncluder.js:64:76

Following componentsjs warning is thrown as well: 

>  [Components.js] warn: Detected potentially invalid IRI 'files-scs:config/util/auxiliary/strategies/meta.json' in C:/Users/Administrator/AppData/Roaming/npm/node_modules/@solid/community-server/config/util/auxiliary/no-acl.json
![console screenshot](https://user-images.githubusercontent.com/98752594/195298994-56ba8db8-360a-42b8-9bad-6ee96fa5b1f1.png)

Note:- The benchmark works, when the git repository is cloned and data is generated and served.

**Comment by rubensworks** [comment]
Thanks for reporting! Looks like a Windows-specific issue.
